---
title: "Works Cited"
format: html
editor: visual
---

\

Bond, M. H., Nodine, T. G., Beechie, T. J., & Zabel, R. W. (2019). Estimating the benefits of widespread floodplain reconnection for Columbia River Chinook salmon. Canadian Journal of Fisheries and Aquatic Sciences, 76(7), 1212–1226.[ https://doi.org/10.1139/cjfas-2018-0108](https://doi.org/10.1139/cjfas-2018-0108)

\

Newhouse, Dan. “Newhouse Introduces Bill to Protect Four Lower Snake River Dams, Clean Energy, Agriculture, and Transportation in the Pacific Northwest.” Office of Representative Dan Newhouse, 23 Mar. 2023, newhouse.house.gov/media-center/press-releases/newhouse-introduces-bill-protect-four-lower-snake-river-dams-clean-energy-agriculture-and-transportation-in-the-pacific-northwest. 

\

Grill, G., Lehner, B., Thieme, M., Geenen, B., Tickner, D., Antonelli, F., Babu, S., Borrelli, P., Cheng, L.,Crochetiere, H., Ehalt Macedo, H., Filgueiras, R., Goichot, M., Higgins, J., Hogan, Z., Lip, B.,McClain, M. E., Meng, J., Mulligan, M., … Zarfl, C. (2019). Mapping the world’s free-flowing rivers.Nature, 569(7755), 215–221.[ https://doi.org/10.1038/s41586-019-1111-9](https://doi.org/10.1038/s41586-019-1111-9)

\

Washington State House Republicans. “Snake and Columbia River dams: Controversy rages between renewablehydroelectric advocates and extremists seeking to remove dams.” Washington State House Republicans, 2025, houserepublicans.wa.gov/case-against-dam-removal/.
